# Generated by Django 3.0 on 2022-08-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220829_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='source',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='expense',
            name='unique_message_id',
            field=models.CharField(default='', max_length=256),
        ),
    ]
