# Generated by Django 3.0 on 2022-08-30 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220829_1252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenseuser',
            old_name='contact_number',
            new_name='user_id',
        ),
    ]
